development:
  adapter: postgresql
  encoding: unicode
  database: cocktailcentral_development
  pool: 5
  
test:
  adapter: postgresql
  encoding: unicode
  database: cocktailcentral_test
  pool: 5
  